names(output_3) = c("europe_views", "oceania_views", "asia_views", "n_america_views", "s_america_views", "africa_views", "antarctica_views")
cache('output_3')
names(output_4) = c("europe_views", "oceania_views", "asia_views", "n_america_views", "s_america_views", "africa_views", "antarctica_views")
cache('output_4')
names(output_5) = c("europe_views", "oceania_views", "asia_views", "n_america_views", "s_america_views", "africa_views", "antarctica_views")
cache('output_5')
names(output_6) = c("europe_views", "oceania_views", "asia_views", "n_america_views", "s_america_views", "africa_views", "antarctica_views")
cache('output_6')
names(output_7) = c("europe_views", "oceania_views", "asia_views", "n_america_views", "s_america_views", "africa_views", "antarctica_views")
cache('output_7')