names(output_3_view) = c("twenty5_pct_view", "fifty_pct_view", "seventy5_pct_view", "onehundred_pct_view")
names(output_4_view) = c("twenty5_pct_view", "fifty_pct_view", "seventy5_pct_view", "onehundred_pct_view")
names(output_5_view) = c("twenty5_pct_view", "fifty_pct_view", "seventy5_pct_view", "onehundred_pct_view")
names(output_6_view) = c("twenty5_pct_view", "fifty_pct_view", "seventy5_pct_view", "onehundred_pct_view")
names(output_7_view) = c("twenty5_pct_view", "fifty_pct_view", "seventy5_pct_view", "onehundred_pct_view")
